/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: ["selector", '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "var(--color-surface-container-low)",
        "primary-fixed": "var(--color-primary-fixed)",
        "surface-dim": "var(--color-surface-dim)",
        "surface-container": "var(--color-surface-container)",
        primary: "var(--color-primary)",
        "primary-container": "var(--color-primary-container)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "inverse-primary": "var(--color-inverse-primary)",
        "surface-tint": "var(--color-surface-tint)",
        secondary: "var(--color-secondary)",
        error: "var(--color-error)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "on-background": "var(--color-on-background)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        surface: "var(--color-surface)",
        "on-primary": "var(--color-on-primary)",
        "on-secondary": "var(--color-on-secondary)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "tertiary-container": "var(--color-tertiary-container)",
        "secondary-container": "var(--color-secondary-container)",
        "on-surface": "var(--color-on-surface)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "on-error": "var(--color-on-error)",
        background: "var(--color-background)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "error-container": "var(--color-error-container)",
        "surface-container-high": "var(--color-surface-container-high)",
        "on-tertiary": "var(--color-on-tertiary)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "surface-variant": "var(--color-surface-variant)",
        outline: "var(--color-outline)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "outline-variant": "var(--color-outline-variant)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "surface-bright": "var(--color-surface-bright)",
        "inverse-surface": "var(--color-inverse-surface)",
        tertiary: "var(--color-tertiary)",
        "on-error-container": "var(--color-on-error-container)",
        "on-primary-container": "var(--color-on-primary-container)",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
};
